name: Build Windows EXE

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release
      run: cargo build --release

    - name: Upload Build
      uses: actions/upload-artifact@v5
      with:
        name: windows-build
        path: |
          target/release/*.exe
          fonts/**
